name: CustomRaid
version: 2.0.1
main: HoldMyAppleJuice.CustomRaids
author: HoldMyAppleJuice

depend:
  - Citizens
  - Vault
commands:
  highlight:
    description: ...
  craid:
    description: ...
  raidp:
    description: ...
  trader:
    description: ...
  raider:
    description: ...
  participant:
    description: ...

api-version: "1.13"